upstream backend1 { server ms1:3000; }
upstream backend2 { server ms2:3000; }

server {
  listen 80;

  location /api1/ {
    proxy_pass http://backend1/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api2/ {
    proxy_pass http://backend2/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
